# Use an official Apache HTTP server image as the base
FROM httpd:2.4

# Copy the index.html file for version 1 into the Apache web server document root
COPY index-v1.html /usr/local/apache2/htdocs/index.html

# Expose the default HTTP port
EXPOSE 80
